MWPW-128882: Added eventlisteners to review
adobecom/dc pull request #185
Opened 2023-03-31 14:10 UTC by zagi25

Resolves: https://jira.corp.adobe.com/browse/MWPW-128882

Before: https://stage--dc--adobecom.hlx.page/acrobat/online/pdf-to-ppt

After: https://mwpw-128882-user-ratings-not-being-reported--dc--adobecom.hlx.page/acrobat/online/pdf-to-ppt

2023-03-31 15:53 UTC, Blainegunn approved these changes

2023-03-31 22:24 UTC, seanchoi-dev requested changes

2023-03-31 22:24 UTC, seanchoi-dev commented on acrobat/scripts/frictionless.js
> +        if (tooltips.length > 0) {
You don't need this if statement. If length is 0, it will skip forEach() anyway.

2023-04-03 15:05 UTC, TsayAdobe commented
It looks like if a user selects 1, 2, or 3 stars and then writes a comment, it will be a double counting.

2023-04-04 11:39 UTC, zagi25 commented
@Blainegunn @TsayAdobe @seanchoi-dev, I removed listeners from all stars because AEM pages only sends review events after submitting the review. With this change milo page behaves the same.

2023-04-05 20:11 UTC, seanchoi-dev approved these changes

2023-04-06 14:36 UTC, merged