Use Milo's version of locales for config
adobecom/dc pull request #268
Opened 2023-06-20 20:46 UTC by hparra

2023-06-20 21:39 UTC, peller commented on acrobat/scripts/scripts.js
> +  const { locales } = await import(`${miloLibs}/scripts/scripts.js`);
this will make our page load slower.

2023-06-20 21:39 UTC, peller requested changes
let's discuss performance ramifications of this change

2023-06-20 21:46 UTC, hparra commented on acrobat/scripts/scripts.js
> +  const { locales } = await import(`${miloLibs}/scripts/scripts.js`);
Change is in the microseconds. Will be loaded from `/scripts/locales.js` when change is made in Milo. This is POC right now.

2023-06-20 21:49 UTC, peller commented on acrobat/scripts/scripts.js
> +  const { locales } = await import(`${miloLibs}/scripts/scripts.js`);
everything is microseconds.  hundreds of microseconds on a constrained connection.  If this is merged, won't it go live?

2023-06-21 02:22 UTC, peller commented on acrobat/scripts/scripts.js
> +  ] = await Promise.all([
Doing this in parallel is better, but everything that comes before loadArea is critical, so we had inlined this stuff on purpose (even though duplicating code is not the ideal approach)

What is the motivation for changing this?

@Blainegunn

2023-06-21 02:23 UTC, peller commented on acrobat/scripts/scripts.js
> +  ] = await Promise.all([
...ideally we'd have a rollup/webpack builder process our imports and do this for us.

2023-06-21 21:28 UTC, hparra commented
@peller See https://github.com/adobecom/milo/pull/880 and the issue it links to for context. I'll recreate this PR against staging if/when that lands.

2023-06-21 21:28 UTC, closed without merging