MWPW-137308: Added origin-trial meta tag so scheduler.yield() can be used
adobecom/dc pull request #397
Opened 2023-10-03 12:12 UTC by zagi25

Resolves: [MWPW-137308](https://jira.corp.adobe.com/browse/MWPW-137308)

Before: https://stage--dc--adobecom.hlx.live/acrobat/online/pdf-to-ppt
After: https://mwpw-137308-scheduler-yield--dc--adobecom.hlx.live/acrobat/online/pdf-to-ppt

2023-10-03 13:11 UTC, peller commented on acrobat/scripts/scripts.js
> +document.head.appendChild(tokenElement);
```suggestion
const token = getTrialToken();
if (token) {
  const tokenElement = document.createElement('meta');
  tokenElement.httpEquiv = 'origin-trial';
  tokenElement.content = token;
  document.head.appendChild(tokenElement);
}
```

2023-10-03 13:11 UTC, peller commented on acrobat/scripts/scripts.js
> +  if (hostname === 'www.stage.adobe.com' || hostname === 'www.adobe.com') return PROD_TOKEN;
if endsWith(adobe.com) return PROD_TOKEN else return undefined

2023-10-03 13:20 UTC, peller commented on acrobat/scripts/scripts.js
> +  if (hostname === 'www.stage.adobe.com' || hostname === 'www.adobe.com') return PROD_TOKEN;
or simplify and maybe just unconditionally post the meta tag.  The meta tag should be a no-op when running on localhost, so scheduler.yield just won't be available, as would be the case for non-Chrome browsers.  The widget code should tolerate this.

2023-10-05 21:35 UTC, Blainegunn commented
@zagi25 now that you have access to the headers sheet you want to move this there?

2023-10-05 21:35 UTC, Blainegunn requested changes
@zagi25 now that you have access to the headers sheet you want to move this there?

2023-10-06 10:52 UTC, zagi25 commented
As @Blainegunn said we can move the token to the headers doc, so it will be delivered as response header
<img width="1099" alt="Screenshot 2023-10-06 at 12 46 36" src="https://github.com/adobecom/dc/assets/90400759/f10e13d0-f475-41da-bd3c-506e487516db">

There is no need for any code update.
cc: @peller

2023-10-06 10:52 UTC, closed without merging