Match Libs config to match MILO
adobecom/dc pull request #557
Opened 2024-02-21 23:12 UTC by Blainegunn

Match Libs config to match MILO

2024-02-21 23:28 UTC, TsayAdobe commented
Please review the test cases in `scripts.jest.js` and `utils.jest.js`.

2024-02-22 00:54 UTC, TsayAdobe requested changes
We need to enable devs using a local milo.

2024-02-22 00:54 UTC, TsayAdobe commented on test/scripts/scripts.jest.js
> +      expect(config.miloLibs).toEqual('/libs');
When `milolibs=local`, it should be  `http://localhost:6456/libs`

2024-02-22 00:54 UTC, TsayAdobe commented on test/scripts/utils.jest.js
> +    expect(libs).toBe('/libs');
When `milolibs=local`, it should be `http://localhost:6456/libs`

2024-08-05 19:28 UTC, joaquinrivero approved these changes

2024-08-15 14:17 UTC, closed without merging