MWPW-151272
adobecom/dc pull request #674
Opened 2024-05-28 16:30 UTC by Blainegunn

Resolves : [MWPW-151272](https://jira.corp.adobe.com/browse/MWPW-151272)

2024-05-28 16:48 UTC, TsayAdobe approved these changes

2024-05-29 18:06 UTC, joaquinrivero approved these changes

2024-05-31 13:48 UTC, peller approved these changes

2024-05-31 13:54 UTC, peller requested changes
please make the same change here
https://github.com/adobecom/dc/blob/stage/edgeworkers/Acrobat_DC_web_prod/utils/locales.js#L55

2024-06-03 15:50 UTC, peller approved these changes

2024-06-03 18:45 UTC, merged