MWPW-147913: Prevent Users From Uploading When They're Signed In
adobecom/dc pull request #719
Opened 2024-07-22 11:54 UTC by joaquinrivero

Resolves: [MWPW-147913](https://jira.corp.adobe.com/browse/MWPW-147913)

Test url:

https://main--dc--adobecom.hlx.page/acrobat/online/compress-pdf?martech=off
https://mwpw-147913--dc--adobecom.hlx.page/acrobat/online/compress-pdf?martech=off

2024-07-22 20:41 UTC, Blainegunn requested changes
looks like we're dispatching `IMS:Ready` twice in this file. 
Perhaps we should consolidate.
Maybe was can do `dropZoneContent.style.pointerEvents = 'none';` with `.css` and then remove it after IMS loads?

2024-07-23 01:02 UTC, joaquinrivero reviewed
@Blainegunn I will find another way to get it properly

2024-07-23 07:29 UTC, saragajic11 approved these changes

2024-07-23 14:56 UTC, peller commented
❗  this covers a corner case but could degrade performance significantly for all users and may miss new cases for error handling

2024-08-06 16:27 UTC, peller commented on acrobat/scripts/scripts.js
> +const { default: dcLoadIMS } = await import('./dcIMS.js');
also FYI this import adds delay to the startup, so we generally try to inline code here or make the inlining happen in the edgeworker as needed

2024-08-07 16:18 UTC, closed without merging