Analytics for acom widget
adobecom/dc pull request #773
Opened 2024-08-22 12:03 UTC by saragajic11

resolves: [MWPW-154526](https://jira.corp.adobe.com/browse/MWPW-154526)

2024-08-25 18:45 UTC, Blainegunn requested changes
@saragajic11 I know you built this based on the example used on the mobile widget. 
I think we should consolidate all these analytics into a single JS file. 
We can also delete lines 7 -24 we don't need anyone of those values. 
Other than that, this is perfect.

2024-08-27 07:55 UTC, saragajic11 commented
> @saragajic11 I know you built this based on the example used on the mobile widget. I think we should consolidate all these analytics into a single JS file. We can also delete lines 7 -24 we don't need anyone of those values. Other than that, this is perfect.

Hi @Blainegunn , I have done some refactoring and put all analytics for acom_widget in one file. Please check the following [commit](https://github.com/adobecom/dc/pull/773/commits/79807b3c4fa805ae13c3165eb039e594566578ca)

2024-08-27 19:45 UTC, Blainegunn approved these changes

2024-08-28 23:43 UTC, TsayAdobe approved these changes

2024-08-28 23:43 UTC, TsayAdobe commented on acrobat/scripts/alloy/acom-widget.js
> +    if (window?._satellite?.track) {
The `window` object doesn't need the optional chaining.

2024-09-03 13:48 UTC, Blainegunn approved these changes

2024-09-03 13:48 UTC, merged