MWPW-161779: Inconsistencies on SUSI link when using right click on sign in CTA on marquee
adobecom/dc pull request #894
Opened 2024-11-14 03:56 UTC by joaquinrivero

Resolves: [MWPW-161779](https://jira.corp.adobe.com/browse/MWPW-161779)

Test URL:

Before: https://main--dc--adobecom.hlx.live/acrobat/online
After: https://mwpw-161779--dc--adobecom.hlx.live/acrobat/online

2024-11-20 16:05 UTC, TsayAdobe commented on acrobat/scripts/susiAuthHandler.js
> +  window.adobeIMS.signUp();
Is it `signIn()` or `signUp()`?

2024-11-21 16:36 UTC, TsayAdobe approved these changes

2024-11-21 18:52 UTC, tedAir requested changes
For Safari, FF, right click leads to load https://auth-stg1.services.adobe.com/en_US/index.html?callback=https%3A%2F%2Fims-na1-stg1.adobelogin.com%2Fims%2Fadobeid%2Facrobatmiloguest%2FAdobeID%2Ftoken%3Fredirect_uri%3Dhttps%253A%252F%252Fwww.stage.adobe.com%252Fhome%26state%3D%257B%2522jslibver%2522%253A%2522v2-v0.45.0-8-gd14e654%2522%252C%2522nonce%2522%253A%25223518218161222912%2522%257D%26code_challenge_method%3Dplain%26use_ms_for_expiry%3Dtrue&client_id=acrobatmiloguest&scope=AdobeID%2Copenid%2Cgnav%2Cadditional_info.roles%2Cread_organizations%2Cpps.read%2CDCAPI&state=%7B%22jslibver%22%3A%22v2-v0.45.0-8-gd14e654%22%2C%22nonce%22%3A%223518218161222912%22%7D&relay=1652b8ae-fe53-4b3e-a78e-f753f9738d51&locale=en_US&flow_type=token&idp_flow_type=login&s_p=google%2Cfacebook%2Capple%2Cmicrosoft%2Cline%2Ckakao&response_type=token&code_challenge_method=plain&redirect_uri=https%3A%2F%2Fwww.stage.adobe.com%2Fhome&use_ms_for_expiry=true#/ , which is inconsistent with the behavior on Chrome. The behavior should be consistent on all browsers.

2024-12-03 05:34 UTC, joaquinrivero commented
Closing this PR since we are not longer need this logic.

2024-12-03 05:34 UTC, closed without merging